events {
    worker_connections 1024;
}

http {
    upstream inventory_backend {
        server inventory_service:3001;
    }

    server {
        listen 4000;

        location / {
            proxy_pass http://inventory_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
